spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: root
    password: 123456